
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int schema_property = 77;
  public static final int BOOL = 94;
  public static final int OAuth2flowType = 65;
  public static final int RefreshUrl = 63;
  public static final int maxLength = 51;
  public static final int Parameter = 30;
  public static final int summ = 81;
  public static final int loc = 71;
  public static final int Tag = 33;
  public static final int c_url = 37;
  public static final int c_name = 38;
  public static final int OpenIdConnectUrl = 61;
  public static final int email = 41;
  public static final int Server = 24;
  public static final int maxProperties = 49;
  public static final int COMMA = 8;
  public static final int BETWEEN_KW = 14;
  public static final int ident = 96;
  public static final int format = 60;
  public static final int TokenUrl = 64;
  public static final int method = 75;
  public static final int minProperties = 48;
  public static final int url = 43;
  public static final int WHERE_KW = 15;
  public static final int desc = 46;
  public static final int uri = 97;
  public static final int SELECT_KW = 18;
  public static final int AGGR_TK = 7;
  public static final int Security = 25;
  public static final int LIMIT_KW = 19;
  public static final int PREFIX_KW = 17;
  public static final int emValue = 72;
  public static final int sCodeRange = 44;
  public static final int Response = 21;
  public static final int string = 93;
  public static final int in = 58;
  public static final int maxCount = 56;
  public static final int Request = 22;
  public static final int minCount = 55;
  public static final int res = 73;
  public static final int NUMBER = 84;
  public static final int req = 70;
  public static final int ORDER_KW = 92;
  public static final int R_CULR_BRACK = 5;
  public static final int contentType = 78;
  public static final int LPAR = 2;
  public static final int ResponseHeader = 27;
  public static final int style = 69;
  public static final int path = 76;
  public static final int type = 52;
  public static final int RequestHeader = 28;
  public static final int l_name = 39;
  public static final int Header = 29;
  public static final int ex_doc_url = 35;
  public static final int ex_doc_desc = 36;
  public static final int DOT = 9;
  public static final int name = 68;
  public static final int Schema = 31;
  public static final int scheme = 67;
  public static final int minLength = 50;
  public static final int COMPARATORS = 13;
  public static final int b_desc = 82;
  public static final int OR_KW = 10;
  public static final int EOF = 0;
  public static final int RPAR = 3;
  public static final int depr = 74;
  public static final int COL = 6;
  public static final int Service = 23;
  public static final int accepted_methods = 85;
  public static final int AKname = 59;
  public static final int header_property = 79;
  public static final int flow_types = 91;
  public static final int DISTINCT_KW = 20;
  public static final int OFFSET_KW = 16;
  public static final int property = 47;
  public static final int error = 1;
  public static final int SecurityScope = 26;
  public static final int AuthUrl = 62;
  public static final int resXX = 86;
  public static final int OPT_KW = 12;
  public static final int vers = 42;
  public static final int maximum = 53;
  public static final int tag_property = 80;
  public static final int NOT_KW = 11;
  public static final int sCode = 45;
  public static final int Property_class = 32;
  public static final int styles = 88;
  public static final int dataType = 57;
  public static final int title_property = 34;
  public static final int var = 95;
  public static final int minimum = 54;
  public static final int sec_types = 87;
  public static final int opName = 83;
  public static final int common_types = 90;
  public static final int L_CULR_BRACK = 4;
  public static final int in_pos = 89;
  public static final int l_des = 40;
  public static final int securityType = 66;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAR",
  "RPAR",
  "L_CULR_BRACK",
  "R_CULR_BRACK",
  "COL",
  "AGGR_TK",
  "COMMA",
  "DOT",
  "OR_KW",
  "NOT_KW",
  "OPT_KW",
  "COMPARATORS",
  "BETWEEN_KW",
  "WHERE_KW",
  "OFFSET_KW",
  "PREFIX_KW",
  "SELECT_KW",
  "LIMIT_KW",
  "DISTINCT_KW",
  "Response",
  "Request",
  "Service",
  "Server",
  "Security",
  "SecurityScope",
  "ResponseHeader",
  "RequestHeader",
  "Header",
  "Parameter",
  "Schema",
  "Property_class",
  "Tag",
  "title_property",
  "ex_doc_url",
  "ex_doc_desc",
  "c_url",
  "c_name",
  "l_name",
  "l_des",
  "email",
  "vers",
  "url",
  "sCodeRange",
  "sCode",
  "desc",
  "property",
  "minProperties",
  "maxProperties",
  "minLength",
  "maxLength",
  "type",
  "maximum",
  "minimum",
  "minCount",
  "maxCount",
  "dataType",
  "in",
  "AKname",
  "format",
  "OpenIdConnectUrl",
  "AuthUrl",
  "RefreshUrl",
  "TokenUrl",
  "OAuth2flowType",
  "securityType",
  "scheme",
  "name",
  "style",
  "req",
  "loc",
  "emValue",
  "res",
  "depr",
  "method",
  "path",
  "schema_property",
  "contentType",
  "header_property",
  "tag_property",
  "summ",
  "b_desc",
  "opName",
  "NUMBER",
  "accepted_methods",
  "resXX",
  "sec_types",
  "styles",
  "in_pos",
  "common_types",
  "flow_types",
  "ORDER_KW",
  "string",
  "BOOL",
  "var",
  "ident",
  "uri"
  };
}

