FROM tenforce/virtuoso:1.3.1-virtuoso7.2.2

# VOLUME /data ./data

ENV SPARQL_UPDATE=true 
ENV VIRT_SPARQL_MaxQueryExecutionTime=300000
ENV VIRT_SPARQL_MaxQueryCostEstimationTime=1000000
# ENV VIRT_Parameters_NumberOfBuffers=680000
# ENV VIRT_Parameters_MaxDirtyBuffers=500000
ENV DBA_PASSWORD=dba

EXPOSE 1111

EXPOSE 8890
